docker-image:
 image: docker:27
 stage: deploy
 services:
   - docker:27-dind
 variables:
   DOCKER_TLS_CERTDIR: "/certs"
   DOCKER_HOST: "tcp://docker:2376"
   DOCKER_CERT_PATH: "/certs/client"
   DOCKER_TLS_VERIFY: "1"
 script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/group/project/image:latest .
    - docker run $CI_REGISTRY/group/project/image:latest
 rules:
   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH